coverage:
  status:
    patch: off
    project:
      default: false
      server:
        paths: "server/**"
        target: 80%
        threshold: 5%
      client:
        paths: "client/**"
        target: 75%
        threshold: 5%
      daemon:
        paths: "daemon/**"
        target: 75%
        threshold: 5%
      other:
        paths: "cmd/**"
        target: 65%
        threshold: 5%
  range: 50..75
  round: down
  precision: 0
  ignore:
    # ignore all generated files, as we do not control those
    - server/api/grpc/generate.go
    - server/api/grpc/schema/zstor.pb.go
    - client/metastor/encoding/proto/generate.go
    - client/metastor/encoding/proto/metadata.pb.go
    - daemon/api/grpc/generate.go
    - daemon/api/grpc/schema/daemon.pb.go

