// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metadata.proto

package proto

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Metadata struct {
	// namespace defines the namespace of the data,
	// and is chosen by the owner of this data.
	Namespace []byte `protobuf:"bytes,9,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// key defines the key of the data,
	// and is chosen by the owner of this data.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// size in bytes represent the total size of the data before any processing
	TotalSize int64 `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	// storageSize in bytes represents the total size of all chunks,
	// that make up the stored data, combined.
	StorageSize int64 `protobuf:"varint,2,opt,name=storageSize,proto3" json:"storageSize,omitempty"`
	// creationEpoch defines the time this data was initially created,
	// in the Unix epoch format, in nano seconds.
	CreationEpoch int64 `protobuf:"varint,3,opt,name=creationEpoch,proto3" json:"creationEpoch,omitempty"`
	// lastWriteEpoch defines the time this data
	// was last modified (e.g. repaired),
	// in the Unix epoch format, in nano seconds.
	LastWriteEpoch int64 `protobuf:"varint,4,opt,name=lastWriteEpoch,proto3" json:"lastWriteEpoch,omitempty"`
	// chunks is the metadata list of all chunks
	// that make up the data, when combined.
	Chunks []Chunk `protobuf:"bytes,5,rep,name=chunks,proto3" json:"chunks"`
	// maximal size of each chunk
	ChunkSize int32 `protobuf:"varint,10,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
	// previousKey is an optional key to the previous Metadata (node),
	// in case this Metadata (node) is used as part
	// of a reversed/double linked list.
	PreviousKey []byte `protobuf:"bytes,6,opt,name=previousKey,proto3" json:"previousKey,omitempty"`
	// nextKey is an optional key to the next Metadata (node),
	// in case this Metadata (node) is used as part
	// of a (double) linked list.
	NextKey []byte `protobuf:"bytes,7,opt,name=nextKey,proto3" json:"nextKey,omitempty"`
	// userDefined is user defined metadata,
	// in case user want to store additional metadata
	// for the object.
	UserDefined map[string]string `protobuf:"bytes,11,rep,name=userDefined,proto3" json:"userDefined,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Metadata) Reset()      { *m = Metadata{} }
func (*Metadata) ProtoMessage() {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return m.Size()
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

type Chunk struct {
	// size of the chunk in bytes
	SizeInBytes int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// objects defines the metadata of the objects
	// that make up this chunk.
	Objects []Object `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects"`
	// hash contains the checksum/signature of the chunk (data),
	// meaning the data of all objects (of this chunk) combined.
	Hash []byte `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *Chunk) Reset()      { *m = Chunk{} }
func (*Chunk) ProtoMessage() {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{1}
}
func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return m.Size()
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

type Object struct {
	// key of the Object
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// shardID defines the ID of the shard the object is stored on
	ShardID string `protobuf:"bytes,2,opt,name=shardID,proto3" json:"shardID,omitempty"`
}

func (m *Object) Reset()      { *m = Object{} }
func (*Object) ProtoMessage() {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{2}
}
func (m *Object) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Object.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return m.Size()
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Metadata)(nil), "proto.Metadata")
	proto.RegisterMapType((map[string]string)(nil), "proto.Metadata.UserDefinedEntry")
	proto.RegisterType((*Chunk)(nil), "proto.Chunk")
	proto.RegisterType((*Object)(nil), "proto.Object")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x7d, 0x4d, 0x9c, 0xd4, 0xe7, 0xa4, 0x54, 0x27, 0x86, 0x53, 0x85, 0x2e, 0x26, 0x20,
	0x14, 0x21, 0x35, 0x95, 0x80, 0x01, 0x31, 0x30, 0x98, 0x74, 0xa8, 0x10, 0x42, 0x32, 0x20, 0xe6,
	0x8b, 0x73, 0x8d, 0x4d, 0x13, 0x5f, 0xe4, 0x3b, 0x57, 0xa4, 0x13, 0x1f, 0x81, 0x8f, 0xd1, 0x8f,
	0xc0, 0x47, 0xc8, 0x98, 0x8d, 0x4e, 0x11, 0xbe, 0x2c, 0x8c, 0x1d, 0x19, 0x91, 0x9f, 0x1d, 0x25,
	0x54, 0x4c, 0x79, 0xef, 0xf7, 0xfe, 0x17, 0xfd, 0xdf, 0xfb, 0x1b, 0x1f, 0x4c, 0x85, 0xe6, 0x23,
	0xae, 0x79, 0x7f, 0x96, 0x4a, 0x2d, 0x89, 0x0d, 0x3f, 0x47, 0xc7, 0xe3, 0x58, 0x47, 0xd9, 0xb0,
	0x1f, 0xca, 0xe9, 0xc9, 0x58, 0x8e, 0xe5, 0x09, 0xe0, 0x61, 0x76, 0x0e, 0x1d, 0x34, 0x50, 0x95,
	0xaf, 0xba, 0x3f, 0x6b, 0x78, 0xff, 0x5d, 0xf5, 0x47, 0xe4, 0x01, 0x76, 0x12, 0x3e, 0x15, 0x6a,
	0xc6, 0x43, 0x41, 0x1d, 0x0f, 0xf5, 0x5a, 0xc1, 0x16, 0x90, 0x43, 0x5c, 0xbb, 0x10, 0x73, 0x8a,
	0x80, 0x17, 0x25, 0x79, 0x88, 0xeb, 0x2a, 0xbe, 0x12, 0x74, 0xdf, 0x43, 0xbd, 0x9a, 0xdf, 0x36,
	0xab, 0x8e, 0xf3, 0x51, 0x6a, 0x3e, 0xf9, 0x10, 0x5f, 0x89, 0x00, 0x46, 0xc4, 0xc3, 0xae, 0xd2,
	0x32, 0xe5, 0x63, 0x51, 0x40, 0xba, 0x57, 0x28, 0x83, 0x5d, 0x44, 0x1e, 0xe3, 0x76, 0x98, 0x0a,
	0xae, 0x63, 0x99, 0x9c, 0xce, 0x64, 0x18, 0xd1, 0x1a, 0x68, 0xfe, 0x85, 0xe4, 0x09, 0x3e, 0x98,
	0x70, 0xa5, 0x3f, 0xa7, 0xb1, 0x16, 0xa5, 0xac, 0x0e, 0xb2, 0x3b, 0x94, 0x3c, 0xc5, 0x8d, 0x30,
	0xca, 0x92, 0x0b, 0x45, 0x6d, 0xaf, 0xd6, 0x73, 0x9f, 0xb5, 0xca, 0x3d, 0xfb, 0x6f, 0x0a, 0xe8,
	0xd7, 0x17, 0xab, 0x8e, 0x15, 0x54, 0x8a, 0x62, 0x5d, 0xa8, 0xc0, 0x19, 0xf6, 0x50, 0xcf, 0x0e,
	0xb6, 0xa0, 0x70, 0x3e, 0x4b, 0xc5, 0x65, 0x2c, 0x33, 0xf5, 0x56, 0xcc, 0x69, 0x03, 0xd6, 0xde,
	0x45, 0x84, 0xe2, 0x66, 0x22, 0xbe, 0xea, 0x62, 0xda, 0x84, 0xe9, 0xa6, 0x25, 0x3e, 0x76, 0x33,
	0x25, 0xd2, 0x81, 0x38, 0x8f, 0x13, 0x31, 0xa2, 0x2e, 0x58, 0xf1, 0x2a, 0x2b, 0x9b, 0x73, 0xf7,
	0x3f, 0x6d, 0x25, 0xa7, 0x89, 0x4e, 0xe7, 0xc1, 0xee, 0xa3, 0xa3, 0xd7, 0xf8, 0xf0, 0xae, 0x60,
	0x37, 0x02, 0xa7, 0x8c, 0xe0, 0x3e, 0xb6, 0x2f, 0xf9, 0x24, 0x2b, 0x2f, 0xeb, 0x04, 0x65, 0xf3,
	0x6a, 0xef, 0x25, 0xea, 0x4a, 0x6c, 0xc3, 0xd2, 0xe4, 0x51, 0x95, 0x12, 0x82, 0x94, 0xee, 0x99,
	0x55, 0xc7, 0x2d, 0x16, 0x3c, 0x4b, 0xfc, 0xb9, 0x16, 0xaa, 0xca, 0xe9, 0x18, 0x37, 0xe5, 0xf0,
	0x8b, 0x08, 0xb5, 0xa2, 0x7b, 0xe0, 0xb6, 0x5d, 0xb9, 0x7d, 0x0f, 0xb4, 0xba, 0xdc, 0x46, 0x43,
	0x08, 0xae, 0x47, 0x5c, 0x95, 0x59, 0xb5, 0x02, 0xa8, 0xbb, 0x2f, 0x70, 0xa3, 0x14, 0xff, 0xe7,
	0x4b, 0xa1, 0xb8, 0xa9, 0x22, 0x9e, 0x8e, 0xce, 0x06, 0x95, 0xd1, 0x4d, 0xeb, 0x0f, 0x16, 0x39,
	0xb3, 0x96, 0x39, 0xb3, 0x6e, 0x72, 0x66, 0xdd, 0xe6, 0x0c, 0xfd, 0xc9, 0x19, 0xfa, 0x66, 0x18,
	0xba, 0x36, 0x0c, 0xfd, 0x30, 0x0c, 0x2d, 0x0c, 0x43, 0x4b, 0xc3, 0xd0, 0x2f, 0xc3, 0xd0, 0x6f,
	0xc3, 0xac, 0x5b, 0xc3, 0xd0, 0xf7, 0x35, 0xb3, 0xae, 0xd7, 0x0c, 0x2d, 0xd7, 0xcc, 0xba, 0x59,
	0x33, 0x6b, 0xd8, 0x00, 0xb3, 0xcf, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x90, 0x1b, 0x44, 0xc3,
	0x15, 0x03, 0x00, 0x00,
}

func (this *Metadata) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Metadata)
	if !ok {
		that2, ok := that.(Metadata)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if c := bytes.Compare(this.Namespace, that1.Namespace); c != 0 {
		return c
	}
	if c := bytes.Compare(this.Key, that1.Key); c != 0 {
		return c
	}
	if this.TotalSize != that1.TotalSize {
		if this.TotalSize < that1.TotalSize {
			return -1
		}
		return 1
	}
	if this.StorageSize != that1.StorageSize {
		if this.StorageSize < that1.StorageSize {
			return -1
		}
		return 1
	}
	if this.CreationEpoch != that1.CreationEpoch {
		if this.CreationEpoch < that1.CreationEpoch {
			return -1
		}
		return 1
	}
	if this.LastWriteEpoch != that1.LastWriteEpoch {
		if this.LastWriteEpoch < that1.LastWriteEpoch {
			return -1
		}
		return 1
	}
	if len(this.Chunks) != len(that1.Chunks) {
		if len(this.Chunks) < len(that1.Chunks) {
			return -1
		}
		return 1
	}
	for i := range this.Chunks {
		if c := this.Chunks[i].Compare(&that1.Chunks[i]); c != 0 {
			return c
		}
	}
	if this.ChunkSize != that1.ChunkSize {
		if this.ChunkSize < that1.ChunkSize {
			return -1
		}
		return 1
	}
	if c := bytes.Compare(this.PreviousKey, that1.PreviousKey); c != 0 {
		return c
	}
	if c := bytes.Compare(this.NextKey, that1.NextKey); c != 0 {
		return c
	}
	if len(this.UserDefined) != len(that1.UserDefined) {
		if len(this.UserDefined) < len(that1.UserDefined) {
			return -1
		}
		return 1
	}
	for i := range this.UserDefined {
		if this.UserDefined[i] != that1.UserDefined[i] {
			if this.UserDefined[i] < that1.UserDefined[i] {
				return -1
			}
			return 1
		}
	}
	return 0
}
func (this *Chunk) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Chunk)
	if !ok {
		that2, ok := that.(Chunk)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.SizeInBytes != that1.SizeInBytes {
		if this.SizeInBytes < that1.SizeInBytes {
			return -1
		}
		return 1
	}
	if len(this.Objects) != len(that1.Objects) {
		if len(this.Objects) < len(that1.Objects) {
			return -1
		}
		return 1
	}
	for i := range this.Objects {
		if c := this.Objects[i].Compare(&that1.Objects[i]); c != 0 {
			return c
		}
	}
	if c := bytes.Compare(this.Hash, that1.Hash); c != 0 {
		return c
	}
	return 0
}
func (this *Object) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Object)
	if !ok {
		that2, ok := that.(Object)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if c := bytes.Compare(this.Key, that1.Key); c != 0 {
		return c
	}
	if this.ShardID != that1.ShardID {
		if this.ShardID < that1.ShardID {
			return -1
		}
		return 1
	}
	return 0
}
func (this *Metadata) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Metadata)
	if !ok {
		that2, ok := that.(Metadata)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Namespace, that1.Namespace) {
		return false
	}
	if !bytes.Equal(this.Key, that1.Key) {
		return false
	}
	if this.TotalSize != that1.TotalSize {
		return false
	}
	if this.StorageSize != that1.StorageSize {
		return false
	}
	if this.CreationEpoch != that1.CreationEpoch {
		return false
	}
	if this.LastWriteEpoch != that1.LastWriteEpoch {
		return false
	}
	if len(this.Chunks) != len(that1.Chunks) {
		return false
	}
	for i := range this.Chunks {
		if !this.Chunks[i].Equal(&that1.Chunks[i]) {
			return false
		}
	}
	if this.ChunkSize != that1.ChunkSize {
		return false
	}
	if !bytes.Equal(this.PreviousKey, that1.PreviousKey) {
		return false
	}
	if !bytes.Equal(this.NextKey, that1.NextKey) {
		return false
	}
	if len(this.UserDefined) != len(that1.UserDefined) {
		return false
	}
	for i := range this.UserDefined {
		if this.UserDefined[i] != that1.UserDefined[i] {
			return false
		}
	}
	return true
}
func (this *Chunk) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Chunk)
	if !ok {
		that2, ok := that.(Chunk)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.SizeInBytes != that1.SizeInBytes {
		return false
	}
	if len(this.Objects) != len(that1.Objects) {
		return false
	}
	for i := range this.Objects {
		if !this.Objects[i].Equal(&that1.Objects[i]) {
			return false
		}
	}
	if !bytes.Equal(this.Hash, that1.Hash) {
		return false
	}
	return true
}
func (this *Object) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Object)
	if !ok {
		that2, ok := that.(Object)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Key, that1.Key) {
		return false
	}
	if this.ShardID != that1.ShardID {
		return false
	}
	return true
}
func (this *Metadata) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 15)
	s = append(s, "&proto.Metadata{")
	s = append(s, "Namespace: "+fmt.Sprintf("%#v", this.Namespace)+",\n")
	s = append(s, "Key: "+fmt.Sprintf("%#v", this.Key)+",\n")
	s = append(s, "TotalSize: "+fmt.Sprintf("%#v", this.TotalSize)+",\n")
	s = append(s, "StorageSize: "+fmt.Sprintf("%#v", this.StorageSize)+",\n")
	s = append(s, "CreationEpoch: "+fmt.Sprintf("%#v", this.CreationEpoch)+",\n")
	s = append(s, "LastWriteEpoch: "+fmt.Sprintf("%#v", this.LastWriteEpoch)+",\n")
	if this.Chunks != nil {
		vs := make([]Chunk, len(this.Chunks))
		for i := range vs {
			vs[i] = this.Chunks[i]
		}
		s = append(s, "Chunks: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "ChunkSize: "+fmt.Sprintf("%#v", this.ChunkSize)+",\n")
	s = append(s, "PreviousKey: "+fmt.Sprintf("%#v", this.PreviousKey)+",\n")
	s = append(s, "NextKey: "+fmt.Sprintf("%#v", this.NextKey)+",\n")
	keysForUserDefined := make([]string, 0, len(this.UserDefined))
	for k, _ := range this.UserDefined {
		keysForUserDefined = append(keysForUserDefined, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForUserDefined)
	mapStringForUserDefined := "map[string]string{"
	for _, k := range keysForUserDefined {
		mapStringForUserDefined += fmt.Sprintf("%#v: %#v,", k, this.UserDefined[k])
	}
	mapStringForUserDefined += "}"
	if this.UserDefined != nil {
		s = append(s, "UserDefined: "+mapStringForUserDefined+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Chunk) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&proto.Chunk{")
	s = append(s, "SizeInBytes: "+fmt.Sprintf("%#v", this.SizeInBytes)+",\n")
	if this.Objects != nil {
		vs := make([]Object, len(this.Objects))
		for i := range vs {
			vs[i] = this.Objects[i]
		}
		s = append(s, "Objects: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "Hash: "+fmt.Sprintf("%#v", this.Hash)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Object) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&proto.Object{")
	s = append(s, "Key: "+fmt.Sprintf("%#v", this.Key)+",\n")
	s = append(s, "ShardID: "+fmt.Sprintf("%#v", this.ShardID)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringMetadata(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Metadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Metadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Metadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UserDefined) > 0 {
		for k := range m.UserDefined {
			v := m.UserDefined[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintMetadata(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintMetadata(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintMetadata(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x5a
		}
	}
	if m.ChunkSize != 0 {
		i = encodeVarintMetadata(dAtA, i, uint64(m.ChunkSize))
		i--
		dAtA[i] = 0x50
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0x4a
	}
	if m.TotalSize != 0 {
		i = encodeVarintMetadata(dAtA, i, uint64(m.TotalSize))
		i--
		dAtA[i] = 0x40
	}
	if len(m.NextKey) > 0 {
		i -= len(m.NextKey)
		copy(dAtA[i:], m.NextKey)
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.NextKey)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.PreviousKey) > 0 {
		i -= len(m.PreviousKey)
		copy(dAtA[i:], m.PreviousKey)
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.PreviousKey)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Chunks) > 0 {
		for iNdEx := len(m.Chunks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Chunks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMetadata(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.LastWriteEpoch != 0 {
		i = encodeVarintMetadata(dAtA, i, uint64(m.LastWriteEpoch))
		i--
		dAtA[i] = 0x20
	}
	if m.CreationEpoch != 0 {
		i = encodeVarintMetadata(dAtA, i, uint64(m.CreationEpoch))
		i--
		dAtA[i] = 0x18
	}
	if m.StorageSize != 0 {
		i = encodeVarintMetadata(dAtA, i, uint64(m.StorageSize))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Chunk) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Chunk) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Chunk) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Objects) > 0 {
		for iNdEx := len(m.Objects) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Objects[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMetadata(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.SizeInBytes != 0 {
		i = encodeVarintMetadata(dAtA, i, uint64(m.SizeInBytes))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Object) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Object) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Object) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ShardID) > 0 {
		i -= len(m.ShardID)
		copy(dAtA[i:], m.ShardID)
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.ShardID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMetadata(dAtA []byte, offset int, v uint64) int {
	offset -= sovMetadata(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedMetadata(r randyMetadata, easy bool) *Metadata {
	this := &Metadata{}
	v1 := r.Intn(100)
	this.Key = make([]byte, v1)
	for i := 0; i < v1; i++ {
		this.Key[i] = byte(r.Intn(256))
	}
	this.StorageSize = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.StorageSize *= -1
	}
	this.CreationEpoch = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.CreationEpoch *= -1
	}
	this.LastWriteEpoch = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.LastWriteEpoch *= -1
	}
	if r.Intn(5) != 0 {
		v2 := r.Intn(5)
		this.Chunks = make([]Chunk, v2)
		for i := 0; i < v2; i++ {
			v3 := NewPopulatedChunk(r, easy)
			this.Chunks[i] = *v3
		}
	}
	v4 := r.Intn(100)
	this.PreviousKey = make([]byte, v4)
	for i := 0; i < v4; i++ {
		this.PreviousKey[i] = byte(r.Intn(256))
	}
	v5 := r.Intn(100)
	this.NextKey = make([]byte, v5)
	for i := 0; i < v5; i++ {
		this.NextKey[i] = byte(r.Intn(256))
	}
	this.TotalSize = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.TotalSize *= -1
	}
	v6 := r.Intn(100)
	this.Namespace = make([]byte, v6)
	for i := 0; i < v6; i++ {
		this.Namespace[i] = byte(r.Intn(256))
	}
	this.ChunkSize = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.ChunkSize *= -1
	}
	if r.Intn(5) != 0 {
		v7 := r.Intn(10)
		this.UserDefined = make(map[string]string)
		for i := 0; i < v7; i++ {
			this.UserDefined[randStringMetadata(r)] = randStringMetadata(r)
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedChunk(r randyMetadata, easy bool) *Chunk {
	this := &Chunk{}
	this.SizeInBytes = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.SizeInBytes *= -1
	}
	if r.Intn(5) != 0 {
		v8 := r.Intn(5)
		this.Objects = make([]Object, v8)
		for i := 0; i < v8; i++ {
			v9 := NewPopulatedObject(r, easy)
			this.Objects[i] = *v9
		}
	}
	v10 := r.Intn(100)
	this.Hash = make([]byte, v10)
	for i := 0; i < v10; i++ {
		this.Hash[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedObject(r randyMetadata, easy bool) *Object {
	this := &Object{}
	v11 := r.Intn(100)
	this.Key = make([]byte, v11)
	for i := 0; i < v11; i++ {
		this.Key[i] = byte(r.Intn(256))
	}
	this.ShardID = string(randStringMetadata(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyMetadata interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneMetadata(r randyMetadata) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringMetadata(r randyMetadata) string {
	v12 := r.Intn(100)
	tmps := make([]rune, v12)
	for i := 0; i < v12; i++ {
		tmps[i] = randUTF8RuneMetadata(r)
	}
	return string(tmps)
}
func randUnrecognizedMetadata(r randyMetadata, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldMetadata(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldMetadata(dAtA []byte, r randyMetadata, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateMetadata(dAtA, uint64(key))
		v13 := r.Int63()
		if r.Intn(2) == 0 {
			v13 *= -1
		}
		dAtA = encodeVarintPopulateMetadata(dAtA, uint64(v13))
	case 1:
		dAtA = encodeVarintPopulateMetadata(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateMetadata(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateMetadata(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateMetadata(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateMetadata(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Metadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	if m.StorageSize != 0 {
		n += 1 + sovMetadata(uint64(m.StorageSize))
	}
	if m.CreationEpoch != 0 {
		n += 1 + sovMetadata(uint64(m.CreationEpoch))
	}
	if m.LastWriteEpoch != 0 {
		n += 1 + sovMetadata(uint64(m.LastWriteEpoch))
	}
	if len(m.Chunks) > 0 {
		for _, e := range m.Chunks {
			l = e.Size()
			n += 1 + l + sovMetadata(uint64(l))
		}
	}
	l = len(m.PreviousKey)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	l = len(m.NextKey)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	if m.TotalSize != 0 {
		n += 1 + sovMetadata(uint64(m.TotalSize))
	}
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	if m.ChunkSize != 0 {
		n += 1 + sovMetadata(uint64(m.ChunkSize))
	}
	if len(m.UserDefined) > 0 {
		for k, v := range m.UserDefined {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovMetadata(uint64(len(k))) + 1 + len(v) + sovMetadata(uint64(len(v)))
			n += mapEntrySize + 1 + sovMetadata(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *Chunk) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SizeInBytes != 0 {
		n += 1 + sovMetadata(uint64(m.SizeInBytes))
	}
	if len(m.Objects) > 0 {
		for _, e := range m.Objects {
			l = e.Size()
			n += 1 + l + sovMetadata(uint64(l))
		}
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	return n
}

func (m *Object) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	l = len(m.ShardID)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	return n
}

func sovMetadata(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMetadata(x uint64) (n int) {
	return sovMetadata(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Metadata) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForChunks := "[]Chunk{"
	for _, f := range this.Chunks {
		repeatedStringForChunks += strings.Replace(strings.Replace(f.String(), "Chunk", "Chunk", 1), `&`, ``, 1) + ","
	}
	repeatedStringForChunks += "}"
	keysForUserDefined := make([]string, 0, len(this.UserDefined))
	for k, _ := range this.UserDefined {
		keysForUserDefined = append(keysForUserDefined, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForUserDefined)
	mapStringForUserDefined := "map[string]string{"
	for _, k := range keysForUserDefined {
		mapStringForUserDefined += fmt.Sprintf("%v: %v,", k, this.UserDefined[k])
	}
	mapStringForUserDefined += "}"
	s := strings.Join([]string{`&Metadata{`,
		`Key:` + fmt.Sprintf("%v", this.Key) + `,`,
		`StorageSize:` + fmt.Sprintf("%v", this.StorageSize) + `,`,
		`CreationEpoch:` + fmt.Sprintf("%v", this.CreationEpoch) + `,`,
		`LastWriteEpoch:` + fmt.Sprintf("%v", this.LastWriteEpoch) + `,`,
		`Chunks:` + repeatedStringForChunks + `,`,
		`PreviousKey:` + fmt.Sprintf("%v", this.PreviousKey) + `,`,
		`NextKey:` + fmt.Sprintf("%v", this.NextKey) + `,`,
		`TotalSize:` + fmt.Sprintf("%v", this.TotalSize) + `,`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`ChunkSize:` + fmt.Sprintf("%v", this.ChunkSize) + `,`,
		`UserDefined:` + mapStringForUserDefined + `,`,
		`}`,
	}, "")
	return s
}
func (this *Chunk) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForObjects := "[]Object{"
	for _, f := range this.Objects {
		repeatedStringForObjects += strings.Replace(strings.Replace(f.String(), "Object", "Object", 1), `&`, ``, 1) + ","
	}
	repeatedStringForObjects += "}"
	s := strings.Join([]string{`&Chunk{`,
		`SizeInBytes:` + fmt.Sprintf("%v", this.SizeInBytes) + `,`,
		`Objects:` + repeatedStringForObjects + `,`,
		`Hash:` + fmt.Sprintf("%v", this.Hash) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Object) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Object{`,
		`Key:` + fmt.Sprintf("%v", this.Key) + `,`,
		`ShardID:` + fmt.Sprintf("%v", this.ShardID) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringMetadata(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Metadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Metadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Metadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageSize", wireType)
			}
			m.StorageSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StorageSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationEpoch", wireType)
			}
			m.CreationEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationEpoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastWriteEpoch", wireType)
			}
			m.LastWriteEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastWriteEpoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chunks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chunks = append(m.Chunks, Chunk{})
			if err := m.Chunks[len(m.Chunks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreviousKey = append(m.PreviousKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PreviousKey == nil {
				m.PreviousKey = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NextKey = append(m.NextKey[:0], dAtA[iNdEx:postIndex]...)
			if m.NextKey == nil {
				m.NextKey = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSize", wireType)
			}
			m.TotalSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = append(m.Namespace[:0], dAtA[iNdEx:postIndex]...)
			if m.Namespace == nil {
				m.Namespace = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChunkSize", wireType)
			}
			m.ChunkSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChunkSize |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserDefined", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UserDefined == nil {
				m.UserDefined = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMetadata
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMetadata
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthMetadata
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthMetadata
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMetadata
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthMetadata
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthMetadata
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipMetadata(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthMetadata
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.UserDefined[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetadata
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMetadata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Chunk) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Chunk: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Chunk: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SizeInBytes", wireType)
			}
			m.SizeInBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SizeInBytes |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Objects", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Objects = append(m.Objects, Object{})
			if err := m.Objects[len(m.Objects)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetadata
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMetadata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Object) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Object: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Object: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShardID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetadata
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMetadata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMetadata(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMetadata
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMetadata
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMetadata
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMetadata        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMetadata          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMetadata = fmt.Errorf("proto: unexpected end of group")
)
