package rest

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"net/http"

	"github.com/gorilla/mux"
	"github.com/zero-os/0-stor/store/config"
	"github.com/zero-os/0-stor/store/db"
)

// NamespacesInterface is interface for /namespaces root endpoint
type NamespacesInterface interface { // nsidaclPost is the handler for POST /namespaces/{nsid}/acl
	// Create an dataAccessToken for a user. This token gives this user access to the data in this namespace
	nsidaclPost(http.ResponseWriter, *http.Request)
	// DeleteObject is the handler for DELETE /namespaces/{nsid}/objects/{id}
	// Delete object from the KV
	DeleteObject(http.ResponseWriter, *http.Request)
	// HeadObject is the handler for HEAD /namespaces/{nsid}/objects/{id}
	// Test object exists in the KV
	HeadObject(http.ResponseWriter, *http.Request)
	// GetObject is the handler for GET /namespaces/{nsid}/objects/{id}
	// Retrieve object from the KV
	GetObject(http.ResponseWriter, *http.Request)
	// Listobjects is the handler for GET /namespaces/{nsid}/objects
	// List keys of the namespaces
	Listobjects(http.ResponseWriter, *http.Request)
	// Createobject is the handler for POST /namespaces/{nsid}/objects
	// Set an object into the namespace
	Createobject(http.ResponseWriter, *http.Request)
	// nsidreservationidGet is the handler for GET /namespaces/{nsid}/reservation/{id}
	// Return information about a reservation
	nsidreservationidGet(http.ResponseWriter, *http.Request)
	// UpdateReservation is the handler for PUT /namespaces/{nsid}/reservation/{id}
	// Renew an existing reservation
	UpdateReservation(http.ResponseWriter, *http.Request)
	// ListReservations is the handler for GET /namespaces/{nsid}/reservation
	// Return a list of all the existing reservation for the give resource
	ListReservations(http.ResponseWriter, *http.Request)
	// CreateReservation is the handler for POST /namespaces/{nsid}/reservation
	// Create a reservation for the given resource.
	CreateReservation(http.ResponseWriter, *http.Request)
	// StatsNamespace is the handler for GET /namespaces/{nsid}/stats
	// Return usage statistics about this namespace
	StatsNamespace(http.ResponseWriter, *http.Request)
	// Deletensid is the handler for DELETE /namespaces/{nsid}
	// Delete nsid
	Deletensid(http.ResponseWriter, *http.Request)
	// Getnsid is the handler for GET /namespaces/{nsid}
	// Get detail view about nsid
	Getnsid(http.ResponseWriter, *http.Request)
	// Listnamespaces is the handler for GET /namespaces
	// List all namespaces
	Listnamespaces(http.ResponseWriter, *http.Request)
	// Createnamespace is the handler for POST /namespaces
	// Create a new namespace
	Createnamespace(http.ResponseWriter, *http.Request)
	// GetStoreStats is the handler for GET /namespaces/stats
	// Return usage statistics about the whole KV
	GetStoreStats(http.ResponseWriter, *http.Request)
	// UpdateStoreStats is the handler for POST /namespaces/stats
	// Update Global Store statistics and available space
	UpdateStoreStats(http.ResponseWriter, *http.Request)

	// Get db object
	DB() db.DB

	// Get Settings object
	Config() config.Settings
}

// NamespacesInterfaceRoutes is routing for /namespaces root endpoint
func NamespacesInterfaceRoutes(r *mux.Router, i NamespacesInterface) {

	r.HandleFunc("/namespaces/{nsid}/acl", i.nsidaclPost).Methods("POST")
	r.HandleFunc("/namespaces/{nsid}/objects/{id}", i.DeleteObject).Methods("DELETE")
	r.HandleFunc("/namespaces/{nsid}/objects/{id}", i.HeadObject).Methods("HEAD")
	r.HandleFunc("/namespaces/{nsid}/objects/{id}", i.GetObject).Methods("GET")
	r.HandleFunc("/namespaces/{nsid}/objects", i.Listobjects).Methods("GET")
	r.HandleFunc("/namespaces/{nsid}/objects", i.Createobject).Methods("POST")
	r.HandleFunc("/namespaces/{nsid}/reservation/{id}", i.nsidreservationidGet).Methods("GET")
	r.HandleFunc("/namespaces/{nsid}/reservation/{id}", i.UpdateReservation).Methods("PUT")
	r.HandleFunc("/namespaces/{nsid}/reservation", i.ListReservations).Methods("GET")
	r.HandleFunc("/namespaces/{nsid}/reservation", i.CreateReservation).Methods("POST")

	/* namespaces/stats Must come before /namespaces/{nsid}
	   Otherwise it won't match!
	*/
	r.HandleFunc("/namespaces/{nsid}/stats", i.StatsNamespace).Methods("GET")
	// r.HandleFunc("/namespaces/stats", i.UpdateStoreStats).Methods("POST")
	r.HandleFunc("/namespaces/stats", i.GetStoreStats).Methods("GET")
	r.HandleFunc("/namespaces/{nsid}", i.Deletensid).Methods("DELETE")
	r.HandleFunc("/namespaces/{nsid}", i.Getnsid).Methods("GET")
	r.HandleFunc("/namespaces", i.Listnamespaces).Methods("GET")
	r.HandleFunc("/namespaces", i.Createnamespace).Methods("POST")
}
